spring.application.name=api

spring.mongodb.uri=mongodb+srv://jcrum1115_db_user:pass123@cluster0.gkf98zw.mongodb.net/project_management?appName=Cluster0

jwt.secret=change-this-to-a-secure-random-256-bit-secret-value
jwt.expiration=86400000